# Generated by Django 6.0 on 2026-01-12 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='qualifications',
            new_name='description',
        ),
    ]
