# Generated by Django 6.0 on 2026-06-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='display_order',
            field=models.IntegerField(default=100, help_text='Priority sorting: lower numbers come first.'),
        ),
    ]
