# Generated by Django 6.0 on 2026-01-12 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_rename_qualifications_doctor_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='description',
            new_name='info',
        ),
    ]
