# Generated by Django 6.0 on 2026-07-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_doctor_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
