# Generated by Django 6.0 on 2026-01-12 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_rename_description_doctor_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='info',
            new_name='description',
        ),
    ]
