# Generated by Django 6.0 on 2026-06-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=150)),
                ('department', models.CharField(help_text='e.g., Cardiology, Oncology', max_length=100)),
                ('testimonial_type', models.CharField(choices=[('image', 'Image Quote'), ('video', 'YouTube Video')], default='image', max_length=10)),
                ('review_text', models.TextField(blank=True, help_text='Written review content', null=True)),
                ('media_url', models.URLField(help_text='Cloudinary image URL or YouTube video link', max_length=500)),
                ('display_order', models.IntegerField(default=100, help_text='Lower numbers show first')),
                ('is_visible', models.BooleanField(default=True, help_text='Uncheck to temporarily hide from public page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
