# Generated by Django 6.0 on 2026-06-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='media_url',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload a photo if type is Image Quote', null=True, upload_to='testimonials/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='video_url',
            field=models.URLField(blank=True, help_text='Paste YouTube link if type is YouTube Video', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='display_order',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
